baseURL = "https://ty888.github.io/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 是否使用 robots.txt
enableRobotsTXT = true
# 是否使用 emoji 代码
enableEmoji = true
# 网站标题
title = "星辰"
keywords = ["博客", "Ty"]
description = "Ty的个人博客"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

#[params]
#  # LoveIt 主题版本
 version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "life"
    pre = ""
    name = "生活"
    url = "/life/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "notes"
    pre = ""
    name = "随记"
    url = "/notes/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "about"
    pre = ""
    name = "关于"
    url = "/about/"
    title = "关于Ty"
    weight = 7

[params]
  # LoveIt theme version
  # LoveIt 主题版本
  version = "0.2.X"
  # public git repo url only then enableGitInfo is true
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = "https://github.com/dillonzq/LoveIt"
  # which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
  # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # 网站关键词
  keywords = ["Ty", "博客", "blog"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  [params.search]
    enable = true
    # 搜索引擎的类型 ("lunr", "algolia")
    type = "lunr"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    # LoveIt 新增 | 0.2.1 最大结果数目
    maxResultLength = 10
    # LoveIt 新增 | 0.2.3 结果内容片段长度
    snippetLength = 50
    # LoveIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # LoveIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
  # Header info
  # 页面头部导航栏信息
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"
    [params.header.title]
    #   # LOGO 的 URL
    #   logo = "/ty.png"
    #   # 标题名称
      name = "Ty"
    #   # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    #   pre = ""
    #   # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    #   post = ""
    #   # LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
    #   typeit = true
  # Footer Copyright Info
  # 页面底部版权信息设置
  [params.footer]
    # Site creation time
    custom = ''
    hugo = false
    # 网站创立年份
    since = 2023
    # ICP info only in China (HTML format is allowed)
    # ICP 备案信息，仅在中国使用 (允许使用 HTML 格式)
    # icp = '<a rel="license external nofollow noopener noreffer" href="http://beian.miit.gov.cn/" target="_blank">xx</a>'
    # license info (HTML format is allowed)
    # 许可协议信息 (允许使用 HTML 格式)
    # license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  [params.section]
    # section 页面每页显示文章数量
    paginate = 20
    dateFormat = "2006-01-02"
  [params.list]
    # section 页面每页显示文章数量
    paginate = 20
    dateFormat = "2006-01-02"
  # 文章页面配置
  [params.home]
    # 主页信息设置
    [params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      # gravatarEmail = "3tyang@gmail.com"
      # 主页显示头像的 URL
      # avatarURL = "/ty.png"
      avatarURL = "https://p3-passport.byteacctimg.com/img/user-avatar/e719ca00ee000913aa8dc6cf7a1fa066~180x180.awebp"
      # 主页显示的网站副标题
      subtitle = "不会打游戏的羽毛球爱好者不是好的铲屎官"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      # title = '测试标题'
  # 主页的社交信息设置
  [params.social]
    GitHub = "ty888"
    Email = "3tyang@gmail.com"
    Juejin = "远星"
    Bilibili = "28374083"
    # Weibo = "6319336063"
    # Linkedin = "xxxx"
    Twitter = "@tianyang2022"
    # Instagram = "xxxx"
    # Facebook = "xxxx"
    # Telegram = "xxxx"
    # Medium = "xxxx"
    # Gitlab = "xxxx"
    # Youtubelegacy = "xxxx"
    # Youtubecustom = "xxxx"
    # Youtubechannel = "xxxx"
    # Tumblr ="xxxx"
    # Quora = "xxxx"
    # Keybase = "xxxx"
    # Pinterest = "xxxx"
    # Reddit = "xxxx"
    # Codepen = "xxxx"
    # FreeCodeCamp = "xxxx"
    # Bitbucket = "xxxx"
    # Stackoverflow = "xxxx"
    # Odnoklassniki = "xxxx"
    # VK = "xxxx"
    # Flickr = "xxxx"
    # Xing = "xxxx"
    # Snapchat = "xxxx"
    # Soundcloud = "xxxx"
    # Spotify = "xxxx"
    # Bandcamp = "xxxx"
    # Paypal = "xxxx"
    # Fivehundredpx = "xxxx"
    # Mix = "xxxx"
    # Goodreads = "xxxx"
    # Lastfm = "xxxx"
    # Foursquare = "xxxx"
    # Hackernews = "xxxx"
    # Kickstarter = "xxxx"
    # Patreon = "xxxx"
    # Steam = "xxxx"
    # Twitch = "xxxx"
    # Strava = "xxxx"
    # Skype = "xxxx"
    # Whatsapp = "xxxx"
    # Douban = "xxxx"
    # Angellist = "xxxx"
    # Slidershare = "xxxx"
    # Jsfiddle = "xxxx"
    # Deviantart = "xxxx"
    # Behance = "xxxx"
    # Dribble = "xxxx"
    # Wordpress = "xxxx"
    # Vine = "xxxx"
    # Googlescholar = "xxxx"
    # Researchgate = "xxxx"
    # Mastodon = "xxxx"
    # MastodonPrefix = "https://mastodon.technology/"
    # Thingiverse = "xxxx"
    # Devto = "xxxx"
    # Gitea = "xxxx"
    # XMPP = "xxxx"
    # Matrix = "xxxx"
  # Page config
  # 文章页面配置
  [params.page]
    # whether to use lightgallery in the page
    # 是否在文章页面使用 lightgallery
    lightgallery = true
    # whether to show link to Raw Markdown content of the post
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = false
    # mathematical formulas (KaTeX https://katex.org/)
    # 数学公式 (KaTeX https://katex.org/)

    [params.page.code]
    copy = true
    maxShownLines = 100
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = "pk.eyJ1IjoiamlhbmdiYW8xMTIzIiwiYSI6ImNreTFjeDl3dTAxMWoydm5wY2txdnN3NWYifQ.H4tHuXUVNDWtldkyrXVU2g"
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/streets-v10"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/streets-v10"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = false
      # 是否添加 FullscreenControl
      fullscreen = true
  [params.math]
    enable = true
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # default inline delimiter is $ ... $ and \\( ... \\)
    # 默认内联定界符是 $ ... $ 和 \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX extension copy_tex
    # KaTeX 插件 copy_tex
    copyTex = true
    # KaTeX extension mhchem
    # KaTeX 插件 mhchem
    mhchem = true
  # 文章页面的分享信息设置
  [params.share]
    enable = false
    # Twitter = true
    # Facebook = true
    # Linkedin = true
    # Whatsapp = true
    # Pinterest = true
    # Tumblr = true
    # HackerNews = true
    # Reddit = true
    # VK = true
    # Buffer = true
    # Xing = true
    # Line = true
    # Instapaper = true
    # Pocket = true
    # Digg = true
    # Stumbleupon = true
    # Flipboard = true
    # Weibo = true
    # Renren = true
    # Myspace = true
    # Blogger = true
    # Baidu = true
    # Odnoklassniki = true
    # Evernote = true
    # Skype = true
    # Trello = true
    # Mix = true
  # site verification code for Google/Bing/Yandex/Pinterest/Baidu
  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
  # Publisher Info just for SEO
  # 出版者信息，仅用于 SEO
  [params.publisher]
    name = "Ty"
    [params.publisher.logo]
      url = "ty.png"
      width = 127
      height = 40
  # Website Log Info just for SEO
  # 网站 Logo 信息，仅用于 SEO
  [params.logo]
    url = "ty.png"
    width = 127
    height = 40
  # Website Image Info just for SEO
  # 网站图标信息，仅用于 SEO
  [params.image]
    url = "ty.png"
    width = 800
    height = 600
  # CSS and JS Files CDN
  # CSS 和 JS 文件的 CDN 设置
  [params.cdn]
    # fontawesome-free@5.12.1 https://fontawesome.com/
    fontawesomeFreeCSS = ''
    # animate.css@3.7.2 https://github.com/daneden/animate.css
    animateCSS = ''
    # smooth-scroll@16.1.2 https://github.com/cferdinandi/smooth-scroll
    smoothScrollJS = ''
    # sharer@0.4.0 https://github.com/ellisonleao/sharer.js
    sharerJS = ''
    # lazysizes@5.2.0 https://github.com/aFarkas/lazysizes
    lazysizesJS = ''
    # lightgallery@1.1.3 lg-thumbnail@1.1.0 lg-zoom@1.1.0 https://github.com/sachinchoolur/lightgallery.js
    lightgalleryCSS = ''
    lightgalleryJS = ''
    lightgalleryThumbnailJS = ''
    lightgalleryZoomJS = ''
    # typeit@6.5.1 https://github.com/alexmacarthur/typeit
    typeitJS = ''
    # katex@0.11.1 https://github.com/KaTeX/KaTeX
    katexCSS = ''
    katexJS = ''
    katexAutoRenderJS = ''
    katexCopyTexCSS = ''
    katexCopyTexJS = ''
    katexMhchemJS = ''
    # mermaid@8.4.8 https://github.com/knsv/mermaid
    mermaidJS = ''
    # aplayer@1.10.1 https://github.com/MoePlayer/APlayer
    aplayerCSS = ''
    aplayerJS = ''
    # meting@2.0.1 https://github.com/metowolf/MetingJS
    metingJS = ''
    # echarts@4.6.0 https://echarts.apache.org/
    echartsJS = ''
    echartsMacaronsJS = ''
    # gitalk@1.6.2 https://github.com/gitalk/gitalk
    gitalkCSS = ''
    gitalkJS = ''
    # valine@1.3.10 https://valine.js.org/
    valineJS = ''
  
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-TYXZ2Y2RHZ"
      # 是否匿名化用户 IP
      anonymizeIP = false

# Markup related configuration in Hugo
# Hugo 解析文档的配置
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # Table Of Contents settings
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
# 作者信息
[author]
  name = "Ty"
  link = "https://github.com/ty888"

# Sitemap Info
# 网站地图信息
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
# Permalinks 信息 (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
# 隐私信息设置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
# 用于 Hugo 输出文档的设置
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]